import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: {
    height: "100%",
    backgroundColor: "#f5f5f5",
    borderTopLeftRadius: 50,
  },
  title: {
    color: "#004d40",
    fontSize: 24,
    fontWeight: "bold",
  },
  homeButton: {
    alignItems: "center",
    justifyContent: "center",
    margin: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 50,
    backgroundColor: "pink",
    width: "40%",
    height: "60%",
  },
  footer: {
    backgroundColor: "#004d40",
    flex: 1,
    padding: 10,
    display: "flex",
    flexDirection: "row",
  },
  leafButtonGreen: {
    alignItems: "center",
    justifyContent: "center",
    margin: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 30,
    backgroundColor: "#004d40",
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
  },
  leafButtonPink: {
    alignItems: "center",
    justifyContent: "center",
    margin: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 30,
    backgroundColor: "pink",
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
  },
  arrowLeftButton: {
    alignItems: "center",
    justifyContent: "center",
    margin: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
    backgroundColor: "pink",
  },
  arrowRightButton: {
    alignItems: "center",
    justifyContent: "center",
    margin: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopRightRadius: 50,
    borderBottomRightRadius: 50,
    backgroundColor: "pink",
  },
  buttonVote: {
    alignItems: "center",
    justifyContent: "center",
    margin: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 50,
    backgroundColor: "#004d40",
  },
  buttonVoteDisabled: {
    alignItems: "center",
    justifyContent: "center",
    margin: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "grey",
    borderRadius: 50,
  },
  buttonTextGreen: {
    textAlign: "center",
    textAlignVertical: "center",
    color: "#004d40",
    fontWeight: "bold",
    fontSize: 16,
  },
  buttonTextPink: {
    textAlign: "center",
    textAlignVertical: "center",
    color: "pink",
    fontWeight: "bold",
    fontSize: 16,
  },
  textNormal: {
    color: "#338A3E",
    fontSize: 14,
    fontWeight: "bold",
  },
})

export const navigatorStyle = {
  headerStyle: { backgroundColor: "#004d40" },
  headerTitleAlign: "center",
  headerTintColor: "#FFFFFF",
  headerTitleStyle: { fontFamily: "serif" },
}
